name: Build ImmortalWrt for 360 V6

on:
  # 手动触发工作流
  workflow_dispatch:
  # 定时触发，每周日凌晨 3 点
  schedule:
    - cron: '0 3 * * 0'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache ecj fastjar file g++ gawk \
            gettext git java-propose-classpath libelf-dev libncurses5-dev \
            libncursesw5-dev libssl-dev python3 python3-distutils python3-setuptools \
            python3-dev rsync subversion swig time unzip wget xmlto zlib1g-dev

      - name: Clone ImmortalWrt source code
        run: |
          git clone https://github.com/immortalwrt/immortalwrt.git
          cd immortalwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure target
        run: |
          cd immortalwrt
          cat <<EOF > .config
# Target System
CONFIG_TARGET_ramips=y
CONFIG_TARGET_ramips_mt7621=y
CONFIG_TARGET_ramips_mt7621_DEVICE_360_v6=y

# Kernel
CONFIG_KERNEL_VERSION_5_10=y
CONFIG_KERNEL_ath=y
CONFIG_KERNEL_ath9k=y
CONFIG_KERNEL_ath9k_common=y
CONFIG_KERNEL_ath9k_hw=y
CONFIG_KERNEL_mac80211=y
CONFIG_KERNEL_cfg80211=y
CONFIG_KERNEL_lib80211=y
CONFIG_KERNEL_lib80211_crypt=y
CONFIG_KERNEL_lib80211_crypt_ccmp=y
CONFIG_KERNEL_lib80211_crypt_tkip=y
CONFIG_KERNEL_lib80211_crypt_wep=y
CONFIG_KERNEL_mt76=y
CONFIG_KERNEL_mt7603=y
CONFIG_KERNEL_mt7615e=y
CONFIG_KERNEL_mt7615_firmware=y

# Base system
CONFIG_PACKAGE_base-files=y
CONFIG_PACKAGE_busybox=y
CONFIG_PACKAGE_dnsmasq-full=y
CONFIG_PACKAGE_firewall4=y
CONFIG_PACKAGE_ip=y
CONFIG_PACKAGE_ip6tables=y
CONFIG_PACKAGE_iptables=y
CONFIG_PACKAGE_kmod-ath=y
CONFIG_PACKAGE_kmod-ath9k=y
CONFIG_PACKAGE_kmod-ath9k-common=y
CONFIG_PACKAGE_kmod-ath9k-hw=y
CONFIG_PACKAGE_kmod-cfg80211=y
CONFIG_PACKAGE_kmod-fs-ext4=y
CONFIG_PACKAGE_kmod-ip6tables=y
CONFIG_PACKAGE_kmod-ipt-conntrack=y
CONFIG_PACKAGE_kmod-ipt-core=y
CONFIG_PACKAGE_kmod-ipt-nat=y
CONFIG_PACKAGE_kmod-lib-crc-ccitt=y
CONFIG_PACKAGE_kmod-lib-crc32c=y
CONFIG_PACKAGE_kmod-lib-80211=y
CONFIG_PACKAGE_kmod-lib-80211-crypt-ccmp=y
CONFIG_PACKAGE_kmod-lib-80211-crypt-tkip=y
CONFIG_PACKAGE_kmod-lib-80211-crypt-wep=y
CONFIG_PACKAGE_kmod-mac80211=y
CONFIG_PACKAGE_kmod-mt76=y
CONFIG_PACKAGE_kmod-mt7603=y
CONFIG_PACKAGE_kmod-mt7615e=y
CONFIG_PACKAGE_kmod-mt7615-firmware=y
CONFIG_PACKAGE_kmod-nf-conntrack=y
CONFIG_PACKAGE_kmod-nf-conntrack6=y
CONFIG_PACKAGE_kmod-nf-flowtable=y
CONFIG_PACKAGE_kmod-nf-ipt=y
CONFIG_PACKAGE_kmod-nf-ipt6=y
CONFIG_PACKAGE_kmod-nf-nat=y
CONFIG_PACKAGE_kmod-nf-nat6=y
CONFIG_PACKAGE_kmod-ppp=y
CONFIG_PACKAGE_kmod-pppoe=y
CONFIG_PACKAGE_kmod-pppox=y
CONFIG_PACKAGE_kmod-tun=y
CONFIG_PACKAGE_luci=y
CONFIG_PACKAGE_luci-app-firewall=y
CONFIG_PACKAGE_luci-app-opkg=y
CONFIG_PACKAGE_luci-i18n-base-zh-cn=y
CONFIG_PACKAGE_luci-i18n-firewall-zh-cn=y
CONFIG_PACKAGE_luci-i18n-opkg-zh-cn=y
CONFIG_PACKAGE_luci-proto-ppp=y
CONFIG_PACKAGE_luci-theme-argon=y
CONFIG_PACKAGE_opkg=y

# Network
CONFIG_PACKAGE_dhcpv6-client=y
CONFIG_PACKAGE_dhcpv6-server=y
CONFIG_PACKAGE_ip6tables-mod-nat=y
CONFIG_PACKAGE_iptables-mod-nat=y
CONFIG_PACKAGE_iptables-mod-ipopt=y
CONFIG_PACKAGE_iptables-mod-extra=y
CONFIG_PACKAGE_ppp=y
CONFIG_PACKAGE_ppp-mod-pppoe=y

# LuCI Applications
CONFIG_PACKAGE_luci-app-commands=y
CONFIG_PACKAGE_luci-app-ddns=y
CONFIG_PACKAGE_luci-app-openvpn=y
CONFIG_PACKAGE_luci-app-upnp=y
CONFIG_PACKAGE_luci-app-vlmcsd=y
CONFIG_PACKAGE_luci-app-wireguard=y
CONFIG_PACKAGE_luci-i18n-commands-zh-cn=y
CONFIG_PACKAGE_luci-i18n-ddns-zh-cn=y
CONFIG_PACKAGE_luci-i18n-openvpn-zh-cn=y
CONFIG_PACKAGE_luci-i18n-upnp-zh-cn=y
CONFIG_PACKAGE_luci-i18n-vlmcsd-zh-cn=y
CONFIG_PACKAGE_luci-i18n-wireguard-zh-cn=y

# Utilities
CONFIG_PACKAGE_htop=y
CONFIG_PACKAGE_nano=y
EOF
          make -C immortalwrt defconfig

      - name: Build firmware
        run: |
          cd immortalwrt
          make -j$(nproc) || make -j1 V=s

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v3
        with:
          name: 360v6-immortalwrt-firmware
          path: immortalwrt/bin/targets/ramips/mt7621/*.bin    